version: '3'
services:
    gateway:
        image: "qtz/gateway"
        ports:
            - "80:80"
#        networks:
#            - qtz1
    srv1:
        image: "qtz-c/srv1:0.1"
#        networks:
#            - qtz1
        depends_on:
            - gateway
    srv2:
        image: "qtz-c/srv2:0.1"
#        networks:
#            - qtz1
        depends_on:
            - gateway
#    redis:
#        image: qtz/
#        ports:
#            - "6379:6379"
#        command: ['mysqld', '--character-set-server=utf8']
#        networks:
#            - qtz
#volumes:
#    mysql-data:

#networks:
#    qtz1:
