version: '3'
services:
    gateway:
        image: "sctek:5000/qtz-gateway"
        ports:
            - "80:80"
        networks:
            - qtzstack
    srv1:
        image: "sctek:5000/qtz-srv1"
        networks:
            - qtzstack
        #depends_on:
        #    - gateway
    srv2:
        image: "sctek:5000/qtz-srv2"
        networks:
            - qtzstack
        depends_on:
            - gateway
#    redis:
#        image: qtz/
#        ports:
#            - "6379:6379"
#        command: ['mysqld', '--character-set-server=utf8']
#        networks:
#            - qtz
#volumes:
#    mysql-data:

networks:
    qtzstack:
