version: '2'
services:
    gateway:
        image: "sctek:5000/qtz-gateway"
        ports:
            - "80:80"
        networks:
            - qtz
    srv1:
        image: "sctek:5000/qtz-srv1"
        networks:
            - qtz
        depends_on:
            - gateway
    srv2:
        image: "sctek:5000/qtz-srv2"
        networks:
            - qtz
        depends_on:
            - gateway
#    redis:
#        image: qtz/
#        ports:
#            - "6379:6379"
#        command: ['mysqld', '--character-set-server=utf8']
#        networks:
#            - qtz
#volumes:
#    mysql-data:

networks:
    qtz:
