version: '3'
services:
    nginx:
        image: "192.168.1.128:5000/lnmp:nginx"
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - php
        #command: ./wait-for-it.sh php:9000 -- echo php started...
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
    php:
        image: "192.168.1.128:5000/lnmp:php"
        networks:
            - frontend
            - backend
        environment:
            MYSQL_PASSWORD: 111
        depends_on:
            - mysql
        deploy:
          replicas: 1
          restart_policy:
            condition: on-failure
networks:
    frontend:
    backend:

